### PR TITLE
fix(k8s-context): use the context passed in SpinnakerService when validating Kubernetes accounts.

### LINKED ISSUE #172: Validator doesn't properly handle k8s context
The Validator throws an error when you feed kubeconfig with multiple k8s clusters and without default contexts.
```
SpinnakerService validation failed:
Validator for account 'AKS-0' detected an error:
  Error listing pods in account "AKS-0", namespace "test":
  pods is forbidden: User "system:serviceaccount:kube-system:spinnaker-service-account" cannot list resource "pods" in API group "" in the namespace "test"
```
although same kubeconfig file works fine with Halyard. The kubeconfig is valid and has all permissions:
```
kubectl auth  can-i get pods --kubeconfig=test --context=aks-0 -n test
yes
```
Here is the account config:
```
providers:
  kubernetes:
    enabled: true
    primaryAccount: AKS-0
    accounts:
    - name: AKS-0
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: aks-0
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces:
      - test
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: encryptedFile:k8s!n:spinnaker-secrets!k:kubeconfigFile
      liveManifestCalls: true
      oAuthScopes: []
      onlySpinnakerManaged: true
      checkPermissionsOnStartup: true
```
Spinnaker Operator works with:
```
spec:
  validation:
    providers:
      kubernetes:
        enabled: false
```
After a deployment clouddriver doesn’t complain. All deployments work just fine. UI works as expected. Logs are fine too:
```
2020-09-16 00:10:42.683  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping artifact has 199 entries and 0 relationships
2020-09-16 00:10:42.683  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping ingress has 22 entries and 66 relationships
2020-09-16 00:10:42.683  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping pod has 984 entries and 983 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping service has 34 entries and 353 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping podDisruptionBudget has 49 entries and 0 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping horizontalpodautoscaler has 49 entries and 0 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping replicaSet has 413 entries and 2485 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping clusters has 101 entries and 615 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping deployment has 45 entries and 503 relationships
2020-09-16 00:10:42.684  INFO 1 --- [ecutionAction-2] n.s.c.k.c.a.KubernetesCacheDataConverter : AKS-0/KubernetesCoreCachingAgent[1/1]: grouping applications has 32 entries and 615 relationships
```

### PR DESCRIPTION
**Pull request by cristhian-castaneda**
Fix the issue that ignores the context given on the SpinnakerService when validating Kubernetes accounts.

Fixes #172

### CODE REVIEW

File: pkg/accounts/kubernetes/validator.go [hunk 1]
```diff
@@ -122,33 +131,44 @@ func makeClientFromSecretRef(ctx context.Context, ref *interfaces.SecretInNamesp
 	if err != nil {
 		return nil, err
 	}
-	return config.ClientConfig()
+
+	cfg, err := config.RawConfig()
+	if err != nil {
+		return nil, fmt.Errorf("Error parsing kubeconfigFile:\n  %w\n  kubeconfigFile contents:\n\n%s", err, str)
```
Comment (ncknt) [inline pkg/accounts/kubernetes/validator.go:137]: Go errors generally start with lowercase. 
'd also not log the kubeconfig content as it may contain tokens.

File: pkg/accounts/kubernetes/validator.go [hunk 2]
```diff
@@ -122,33 +131,44 @@ func makeClientFromSecretRef(ctx context.Context, ref *interfaces.SecretInNamesp
...
 
 // makeClientFromConfigAPI makes a client config from the v1 Config (the usual format for kubeconfig) inlined
 // into the CRD.
-func makeClientFromConfigAPI(config *clientcmdv1.Config) (*rest.Config, error) {
+func makeClientFromConfigAPI(config *clientcmdv1.Config, settings *authSettings) (*rest.Config, error) {
 	cfg := clientcmdapi.NewConfig()
 	if err := clientcmdlatest.Scheme.Convert(config, cfg, nil); err != nil {
 		return nil, nil
 	}
+	if settings.Context != "" {
```
Comment (ncknt) [inline pkg/accounts/kubernetes/validator.go:152]: If settings cannot be nil, don't pass as pointer.

As a side note, I understand why we'd support `context` here for consistency but in effect the user would be defining a kubeconfig with multiple contexts but only one is used (in a secret it makes sense since the kubeconfig can be shared):

```
kind: SpinnakerAccount
spec:
  type: Kubernetes
  kubernetes:
    kubeconfig:
      <inlined kubeconfig>
    settings:
      context: the-context-i-want  
```

File: pkg/accounts/kubernetes/validator.go (hunk 1 above)
Comment (ncknt) [reply pkg/accounts/kubernetes/validator.go]: As I write this I realize, this is already done multiple times in that same file. I don't think it's a good idea.

File: pkg/accounts/kubernetes/validator.go [hunk 3]
```diff
@@ -53,19 +53,27 @@ func (k *kubernetesAccountValidator) Validate(spinSvc interfaces.SpinnakerServic
 }
 
 func (k *kubernetesAccountValidator) makeClient(ctx context.Context, spinSvc interfaces.SpinnakerService, c client.Client) (*rest.Config, error) {
+	aSettings := &authSettings{}
```
Comment (ncknt) [inline pkg/accounts/kubernetes/validator.go:56]: Why not `aSettings := authSettings{}` and just pass aSettings below?

**Comment by ncknt** [comment]
Thanks for the error message cleanup! I've approved but still wonder why we would not pass the `context` instead of the `authSettings` to each function. Each function would get just what it needs.

**Review by ncknt — APPROVED** [review]

**Comment by cristhian-castaneda** [comment]
Thanks for your comment, I just realized that this method `makeOverrideFromAuthSettings` is doing what I tried to do by myself, just needed to reuse it.
